"""create exam answers table

Revision ID: 1b7aa845dad6
Revises: c0f0c66f2a45
Create Date: 2026-07-21 02:28:00.013006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b7aa845dad6'
down_revision: Union[str, Sequence[str], None] = 'c0f0c66f2a45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_answers',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('typed_answer', sa.Text(), nullable=True),
    sa.Column('selected_option', sa.String(length=10), nullable=True),
    sa.Column('handwriting_image', sa.String(length=1000), nullable=True),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('ai_marks', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('max_marks', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('ai_feedback', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['exam_questions.id'], name=op.f('fk_exam_answers_question_id_exam_questions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['exam_sessions.id'], name=op.f('fk_exam_answers_session_id_exam_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_answers'))
    )
    op.create_index(op.f('ix_exam_answers_question_id'), 'exam_answers', ['question_id'], unique=False)
    op.create_index(op.f('ix_exam_answers_session_id'), 'exam_answers', ['session_id'], unique=False)
    op.alter_column('exam_sessions', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('exam_sessions', 'ends_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('exam_sessions', 'submitted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exam_sessions', 'submitted_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('exam_sessions', 'ends_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('exam_sessions', 'started_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('ix_exam_answers_session_id'), table_name='exam_answers')
    op.drop_index(op.f('ix_exam_answers_question_id'), table_name='exam_answers')
    op.drop_table('exam_answers')
    # ### end Alembic commands ###
