"""create knowledge sources table

Revision ID: 43d856437cef
Revises: e3a2ff622b00
Create Date: 2026-07-20 19:53:35.809039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43d856437cef'
down_revision: Union[str, Sequence[str], None] = 'e3a2ff622b00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_sources',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_name', sa.String(length=500), nullable=True),
    sa.Column('file_path', sa.String(length=1000), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('cleaned_text', sa.Text(), nullable=True),
    sa.Column('ocr_completed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('processing_status', sa.String(length=50), server_default='pending', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_knowledge_sources_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_sources'))
    )
    op.create_index('ix_knowledge_source_type', 'knowledge_sources', ['source_type'], unique=False)
    op.create_index('ix_knowledge_status', 'knowledge_sources', ['processing_status'], unique=False)
    op.create_index('ix_knowledge_user_id', 'knowledge_sources', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_knowledge_user_id', table_name='knowledge_sources')
    op.drop_index('ix_knowledge_status', table_name='knowledge_sources')
    op.drop_index('ix_knowledge_source_type', table_name='knowledge_sources')
    op.drop_table('knowledge_sources')
    # ### end Alembic commands ###
