"""initial schema

Revision ID: b23e2c648741
Revises: 
Create Date: 2026-07-26 18:12:49.313707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b23e2c648741'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('education_level', sa.String(length=100), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_index('ix_users_is_active', 'users', ['is_active'], unique=False)
    op.create_table('study_materials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('file_type', sa.Enum('PDF', 'DOCX', 'PPTX', 'TXT', 'MD', 'PNG', 'JPG', 'JPEG', 'WEBP', 'BMP', 'GIF', 'TOPIC', name='materialtype'), nullable=False),
    sa.Column('mime_type', sa.String(length=150), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('processing_status', sa.Enum('UPLOADING', 'EXTRACTING', 'PROCESSING', 'READY', 'FAILED', name='processingstatus'), nullable=False),
    sa.Column('extraction_error', sa.Text(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_study_materials_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_materials')),
    sa.UniqueConstraint('stored_filename', name=op.f('uq_study_materials_stored_filename'))
    )
    op.create_index(op.f('ix_study_materials_file_type'), 'study_materials', ['file_type'], unique=False)
    op.create_index(op.f('ix_study_materials_owner_id'), 'study_materials', ['owner_id'], unique=False)
    op.create_index(op.f('ix_study_materials_processing_status'), 'study_materials', ['processing_status'], unique=False)
    op.create_table('exam_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.Column('exam_type', sa.Enum('OBJECTIVE', 'THEORY', 'MIXED', name='examtype'), nullable=False),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='examdifficulty'), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'IN_PROGRESS', 'SUBMITTED', 'GRADING', 'GRADED', 'EXPIRED', 'FAILED', name='examstatus'), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('total_marks', sa.Integer(), nullable=False),
    sa.Column('obtained_marks', sa.Integer(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['study_materials.id'], name=op.f('fk_exam_sessions_material_id_study_materials'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_exam_sessions_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_sessions'))
    )
    op.create_index(op.f('ix_exam_sessions_material_id'), 'exam_sessions', ['material_id'], unique=False)
    op.create_index(op.f('ix_exam_sessions_owner_id'), 'exam_sessions', ['owner_id'], unique=False)
    op.create_index(op.f('ix_exam_sessions_status'), 'exam_sessions', ['status'], unique=False)
    op.create_table('knowledge_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'READY', 'FAILED', name='knowledgestatus'), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('knowledge', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('topics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('glossary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('learning_objectives', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('key_points', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sample_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('ai_provider', sa.Text(), nullable=True),
    sa.Column('ai_model', sa.Text(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('is_cached', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['study_materials.id'], name=op.f('fk_knowledge_sources_material_id_study_materials'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_sources'))
    )
    op.create_index(op.f('ix_knowledge_sources_material_id'), 'knowledge_sources', ['material_id'], unique=True)
    op.create_index(op.f('ix_knowledge_sources_status'), 'knowledge_sources', ['status'], unique=False)
    op.create_table('exam_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.Enum('OBJECTIVE', 'THEORY', name='questiontype'), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('difficulty', sa.String(length=50), nullable=False),
    sa.Column('marks', sa.Integer(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correct_answer', sa.String(length=10), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('subquestions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('marking_scheme', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_answer', sa.Text(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['exam_sessions.id'], name=op.f('fk_exam_questions_session_id_exam_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_questions'))
    )
    op.create_index(op.f('ix_exam_questions_session_id'), 'exam_questions', ['session_id'], unique=False)
    op.create_table('exam_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('total_marks', sa.Integer(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('objective_score', sa.Integer(), nullable=False),
    sa.Column('theory_score', sa.Integer(), nullable=False),
    sa.Column('correct_answers', sa.Integer(), nullable=False),
    sa.Column('incorrect_answers', sa.Integer(), nullable=False),
    sa.Column('unanswered_questions', sa.Integer(), nullable=False),
    sa.Column('topic_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('weaknesses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['study_materials.id'], name=op.f('fk_exam_results_material_id_study_materials'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_exam_results_owner_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['exam_sessions.id'], name=op.f('fk_exam_results_session_id_exam_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_results'))
    )
    op.create_index(op.f('ix_exam_results_material_id'), 'exam_results', ['material_id'], unique=False)
    op.create_index(op.f('ix_exam_results_owner_id'), 'exam_results', ['owner_id'], unique=False)
    op.create_index(op.f('ix_exam_results_session_id'), 'exam_results', ['session_id'], unique=True)
    op.create_table('exam_submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'AUTOSAVED', 'SUBMITTED', 'GRADING', 'GRADED', 'FAILED', name='submissionstatus'), nullable=False),
    sa.Column('submitted_answers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('question_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('grading_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('answered_questions', sa.Integer(), nullable=False),
    sa.Column('attachment_count', sa.Integer(), nullable=False),
    sa.Column('contains_handwritten_answers', sa.Boolean(), nullable=False),
    sa.Column('client_version', sa.Text(), nullable=True),
    sa.Column('submission_notes', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('graded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['study_materials.id'], name=op.f('fk_exam_submissions_material_id_study_materials'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_exam_submissions_owner_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['exam_sessions.id'], name=op.f('fk_exam_submissions_session_id_exam_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_submissions'))
    )
    op.create_index(op.f('ix_exam_submissions_material_id'), 'exam_submissions', ['material_id'], unique=False)
    op.create_index(op.f('ix_exam_submissions_owner_id'), 'exam_submissions', ['owner_id'], unique=False)
    op.create_index(op.f('ix_exam_submissions_session_id'), 'exam_submissions', ['session_id'], unique=True)
    op.create_index(op.f('ix_exam_submissions_status'), 'exam_submissions', ['status'], unique=False)
    op.create_table('exam_answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('selected_option', sa.String(length=10), nullable=True),
    sa.Column('text_answer', sa.Text(), nullable=False),
    sa.Column('ocr_answer', sa.Text(), nullable=False),
    sa.Column('final_answer', sa.Text(), nullable=False),
    sa.Column('awarded_marks', sa.Float(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('corrections', sa.Text(), nullable=True),
    sa.Column('suggestions', sa.Text(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['exam_questions.id'], name=op.f('fk_exam_answers_question_id_exam_questions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['exam_sessions.id'], name=op.f('fk_exam_answers_session_id_exam_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_answers'))
    )
    op.create_index(op.f('ix_exam_answers_question_id'), 'exam_answers', ['question_id'], unique=False)
    op.create_index(op.f('ix_exam_answers_session_id'), 'exam_answers', ['session_id'], unique=False)
    op.create_table('exam_answer_attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('answer_id', sa.UUID(), nullable=False),
    sa.Column('attachment_type', sa.Enum('IMAGE', 'PDF', name='attachmenttype'), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('ocr_status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='ocrstatus'), nullable=False),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['exam_answers.id'], name=op.f('fk_exam_answer_attachments_answer_id_exam_answers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_answer_attachments'))
    )
    op.create_index(op.f('ix_exam_answer_attachments_answer_id'), 'exam_answer_attachments', ['answer_id'], unique=False)
    op.create_index(op.f('ix_exam_answer_attachments_ocr_status'), 'exam_answer_attachments', ['ocr_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exam_answer_attachments_ocr_status'), table_name='exam_answer_attachments')
    op.drop_index(op.f('ix_exam_answer_attachments_answer_id'), table_name='exam_answer_attachments')
    op.drop_table('exam_answer_attachments')
    op.drop_index(op.f('ix_exam_answers_session_id'), table_name='exam_answers')
    op.drop_index(op.f('ix_exam_answers_question_id'), table_name='exam_answers')
    op.drop_table('exam_answers')
    op.drop_index(op.f('ix_exam_submissions_status'), table_name='exam_submissions')
    op.drop_index(op.f('ix_exam_submissions_session_id'), table_name='exam_submissions')
    op.drop_index(op.f('ix_exam_submissions_owner_id'), table_name='exam_submissions')
    op.drop_index(op.f('ix_exam_submissions_material_id'), table_name='exam_submissions')
    op.drop_table('exam_submissions')
    op.drop_index(op.f('ix_exam_results_session_id'), table_name='exam_results')
    op.drop_index(op.f('ix_exam_results_owner_id'), table_name='exam_results')
    op.drop_index(op.f('ix_exam_results_material_id'), table_name='exam_results')
    op.drop_table('exam_results')
    op.drop_index(op.f('ix_exam_questions_session_id'), table_name='exam_questions')
    op.drop_table('exam_questions')
    op.drop_index(op.f('ix_knowledge_sources_status'), table_name='knowledge_sources')
    op.drop_index(op.f('ix_knowledge_sources_material_id'), table_name='knowledge_sources')
    op.drop_table('knowledge_sources')
    op.drop_index(op.f('ix_exam_sessions_status'), table_name='exam_sessions')
    op.drop_index(op.f('ix_exam_sessions_owner_id'), table_name='exam_sessions')
    op.drop_index(op.f('ix_exam_sessions_material_id'), table_name='exam_sessions')
    op.drop_table('exam_sessions')
    op.drop_index(op.f('ix_study_materials_processing_status'), table_name='study_materials')
    op.drop_index(op.f('ix_study_materials_owner_id'), table_name='study_materials')
    op.drop_index(op.f('ix_study_materials_file_type'), table_name='study_materials')
    op.drop_table('study_materials')
    op.drop_index('ix_users_is_active', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
