"""add study_material_id to knowledge_sources

Revision ID: bb69d3534d4d
Revises: 5c4f9e8d7a12
Create Date: 2026-07-22 21:54:40.651546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb69d3534d4d'
down_revision: Union[str, Sequence[str], None] = '5c4f9e8d7a12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_sources', sa.Column('study_material_id', sa.Uuid(), nullable=True))
    op.create_unique_constraint(op.f('uq_knowledge_sources_study_material_id'), 'knowledge_sources', ['study_material_id'])
    op.create_foreign_key(op.f('fk_knowledge_sources_study_material_id_study_materials'), 'knowledge_sources', 'study_materials', ['study_material_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_knowledge_sources_study_material_id_study_materials'), 'knowledge_sources', type_='foreignkey')
    op.drop_constraint(op.f('uq_knowledge_sources_study_material_id'), 'knowledge_sources', type_='unique')
    op.drop_column('knowledge_sources', 'study_material_id')
    # ### end Alembic commands ###
