from __future__ import annotations

from uuid import UUID

from pydantic import BaseModel
from pydantic import ConfigDict


class GenerateStudyGuideRequest(BaseModel):
    """
    The frontend only knows about Study Materials.

    The backend will automatically locate the
    corresponding Knowledge Source.
    """

    study_material_id: UUID


class StudyGuideResponse(BaseModel):
    """
    Complete Study Guide generated by Brain Study.

    The frontend simply renders the markdown/text.
    """

    study_guide: str

    model_config = ConfigDict(
        from_attributes=True,
    )

